name: dave
dependencies:
- Flask==3.0.2
- Jinja2 ==3.1.3
- numpy ==1.26.4
- llvmlite== 0.42.0
- numba==0.59.0
- pip==24.0
- python==3.9.10
- werkzeug==3.0.1
- pytest==7.0.1
- gevent==21.8.0
- pip:
  - astropy==5.3
  - requests==2.26.0
  - flask-session==0.4.0
  - hypothesis==6.23.3
  - python-magic==0.4.24
  - pylru==1.2.0
